version: "3.9"

services:
  postgres:
    image: postgres:18
    container_name: postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: restaurant_host
      POSTGRES_USER: mi_user
      POSTGRES_PASSWORD: mi_password
      PGDATA: /var/lib/postgresql/18/docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mi_user -d restaurant_host"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend_restaurantmanager
    container_name: springboot_dev
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/restaurant_host
      SPRING_DATASOURCE_USERNAME: mi_user
      SPRING_DATASOURCE_PASSWORD: mi_password
      JWT_SECRET: Wbp41d@8J&faPLZ0\ml|=R2np')z{Y@t)-6UTren9r3Ev4|t+K
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend_restaurantmanager:/app

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --url http://nginx:80 --protocol http2 --no-autoupdate
    depends_on:
      - nginx

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: