-- =========================================
-- USUARIO BACKEND
-- =========================================

DROP ROLE IF EXISTS admin;
CREATE ROLE admin WITH LOGIN PASSWORD 'admin';

-- =========================================
-- TABLA: restaurants
-- =========================================
CREATE TABLE restaurants (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	prefix VARCHAR(5) NOT NULL,
	name VARCHAR(150) NOT NULL,
	description TEXT,
	email VARCHAR(150) NOT NULL,
	phone VARCHAR(25) NOT NULL,
	address VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_restaurants PRIMARY KEY (id),
	CONSTRAINT uq_restaurants_prefix UNIQUE (prefix),
	CONSTRAINT uq_restaurants_email UNIQUE (email)
);

-- =========================================
-- EMPLOYEES
-- =========================================
CREATE TYPE roles AS ENUM ('MANAGER', 'WAITER', 'COOKER', 'ADMIN');

CREATE TABLE employee (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	restaurant_id INTEGER NOT NULL,
	name VARCHAR(150) NOT NULL,
	role_name roles NOT NULL,
	active BOOLEAN NOT NULL DEFAULT TRUE,
	email VARCHAR(150) NOT NULL,
	phone VARCHAR(25),
	start_date DATE NOT NULL,
	end_date DATE,
	position_notes TEXT,
	code VARCHAR(10),
	password_hash VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_employee PRIMARY KEY (id),
	CONSTRAINT uq_employee_code_per_restaurant
		UNIQUE (restaurant_id, code),
	CONSTRAINT fk_employee_restaurant FOREIGN KEY (restaurant_id)
		REFERENCES restaurants(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- =========================================
-- SCHEDULES
-- =========================================
CREATE TABLE work_schedules (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	employee_id INTEGER NOT NULL,
	start_datetime TIMESTAMP NOT NULL,
	end_datetime TIMESTAMP NOT NULL,
	CONSTRAINT pk_work_schedules PRIMARY KEY (id),
	CONSTRAINT fk_ws_employee FOREIGN KEY (employee_id)
		REFERENCES employee(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT chk_ws_dates CHECK (end_datetime > start_datetime)
);

-- =========================================
-- SECTIONS
-- =========================================
CREATE TABLE table_sections (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	restaurant_id INTEGER NOT NULL,
	title VARCHAR(100) NOT NULL,
	CONSTRAINT pk_table_sections PRIMARY KEY (id),
	CONSTRAINT fk_table_sections_restaurant FOREIGN KEY (restaurant_id)
		REFERENCES restaurants(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TYPE table_status AS ENUM ('AVAILABLE', 'UNAVAILABLE', 'OCCUPIED', 'RESERVED');

-- =========================================
-- TABLES
-- =========================================
CREATE TABLE tables_restaurant (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	restaurant_id INTEGER NOT NULL,
	section_id INTEGER NOT NULL,
	name VARCHAR(50) NOT NULL,
	capacity INTEGER NOT NULL DEFAULT 2,
	pos_x INTEGER NOT NULL DEFAULT 0,
	pos_y INTEGER NOT NULL DEFAULT 0,
	status table_status NOT NULL DEFAULT 'AVAILABLE',
	CONSTRAINT pk_tables_restaurant PRIMARY KEY (id),
	CONSTRAINT fk_tables_restaurant_restaurant FOREIGN KEY (restaurant_id)
		REFERENCES restaurants(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT fk_tables_restaurant_section FOREIGN KEY (section_id)
		REFERENCES table_sections(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- =========================================
-- CATEGORIES DISHES
-- =========================================
CREATE TABLE dishes_categories (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	restaurant_id INTEGER NOT NULL,
	name VARCHAR(100) NOT NULL,
	CONSTRAINT pk_dishes_categories PRIMARY KEY (id),
	CONSTRAINT fk_dishes_categories_restaurant FOREIGN KEY (restaurant_id)
		REFERENCES restaurants(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- =========================================
-- DISHES
-- =========================================
CREATE TABLE dishes (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	restaurant_id INTEGER NOT NULL,
	category_id INTEGER,
	name VARCHAR(150) NOT NULL,
	description TEXT,
	price NUMERIC(10,2) NOT NULL,
	available BOOLEAN NOT NULL DEFAULT TRUE,
	CONSTRAINT pk_dishes PRIMARY KEY (id),
	CONSTRAINT fk_dishes_restaurant FOREIGN KEY (restaurant_id)
		REFERENCES restaurants(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT fk_dishes_category FOREIGN KEY (category_id)
		REFERENCES dishes_categories(id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT uq_dishes_restaurant_name UNIQUE (restaurant_id, name)
);

-- =========================================
-- ORDER STATUS
-- =========================================
CREATE TYPE order_status AS ENUM ('CREATED', 'DELIVERED', 'PAID');

-- =========================================
-- ORDER TYPE
-- =========================================
CREATE TYPE order_type AS ENUM ('TABLE', 'DELIVERY', 'PICKUP');

-- =========================================
-- ORDERS
-- =========================================
CREATE TABLE orders (
  	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  	restaurant_id INTEGER NOT NULL,
  	type order_type NOT NULL,
	status order_status NOT NULL DEFAULT 'CREATED',
	total NUMERIC(10,2) NOT NULL DEFAULT 0.00,
	notes TEXT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_orders PRIMARY KEY (id),
	CONSTRAINT fk_orders_restaurant FOREIGN KEY (restaurant_id)
		REFERENCES restaurants(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE order_table (
  	order_id INTEGER,
  	table_id INTEGER NOT NULL,
	CONSTRAINT pk_order_table PRIMARY KEY (order_id),
    CONSTRAINT fk_order_table FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE ON UPDATE CASCADE,
  	CONSTRAINT fk_order_table_table FOREIGN KEY (table_id) REFERENCES tables_restaurant(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE order_delivery (
	order_id INTEGER,
  	delivery_address VARCHAR(255) NOT NULL,
  	CONSTRAINT pk_order_delivery PRIMARY KEY (order_id),
  	CONSTRAINT fk_order_delivery FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE order_pickup (
  	order_id INTEGER,
  	pickup_time TIMESTAMP,
  	CONSTRAINT pk_order_pickup PRIMARY KEY (order_id),
  	CONSTRAINT fk_order_pickup FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- =========================================
-- ORDER ITEMS STATUS
-- =========================================
CREATE TYPE order_items_status AS ENUM ('CREATED', 'DELIVERED', 'COOKED');

-- =========================================
-- ORDER ITEMS
-- =========================================
CREATE TABLE order_items (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	order_id INTEGER NOT NULL,
	dish_id INTEGER NOT NULL,
	notes TEXT,
	unit_price NUMERIC(10,2) NOT NULL,
	status order_items_status NOT NULL DEFAULT 'CREATED',
	CONSTRAINT pk_order_items PRIMARY KEY (id),
	CONSTRAINT fk_order_items_order FOREIGN KEY (order_id)
		REFERENCES orders(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_order_items_dish FOREIGN KEY (dish_id)
		REFERENCES dishes(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- =========================================
-- PAYMENTS
-- =========================================
CREATE TABLE payments (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	order_id INTEGER NOT NULL,
	method VARCHAR(50) NOT NULL,
	amount NUMERIC(10,2) NOT NULL,
	paid_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_payments PRIMARY KEY (id),
	CONSTRAINT fk_payments_order FOREIGN KEY (order_id)
		REFERENCES orders(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- =========================================
-- CATEGORIES INGREDIENTS
-- =========================================
CREATE TABLE ingredients_categories (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	restaurant_id INTEGER NOT NULL,
	name VARCHAR(100) NOT NULL,
	CONSTRAINT pk_ingredients_categories PRIMARY KEY (id),
	CONSTRAINT fk_ingredients_categories_restaurant FOREIGN KEY (restaurant_id)
		REFERENCES restaurants(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- =========================================
-- INGREDIENTS
-- =========================================
CREATE TABLE ingredients (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	restaurant_id INTEGER NOT NULL,
	category_id INTEGER,
	name VARCHAR(150) NOT NULL,
	unit VARCHAR(50) NOT NULL,
	stock_quantity NUMERIC(12,3) NOT NULL DEFAULT 0,
	cost_unit NUMERIC(10,2),
	minimum_stock NUMERIC(12,3) NOT NULL DEFAULT 0,
	CONSTRAINT pk_ingredients PRIMARY KEY (id),
	CONSTRAINT fk_ingredients_restaurant FOREIGN KEY (restaurant_id)
		REFERENCES restaurants(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT fk_ingredients_category FOREIGN KEY (category_id)
		REFERENCES ingredients_categories(id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT uq_ingredients_restaurant_name UNIQUE (restaurant_id, name)
);

-- =========================================
-- DISH INGREDIENTS
-- =========================================
CREATE TABLE dish_ingredients (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	dish_id INTEGER NOT NULL,
	ingredient_id INTEGER NOT NULL,
	quantity NUMERIC(12,3) NOT NULL,
	CONSTRAINT pk_dish_ingredients PRIMARY KEY (id),
	CONSTRAINT fk_di_dish FOREIGN KEY (dish_id)
		REFERENCES dishes(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_di_ingredient FOREIGN KEY (ingredient_id)
		REFERENCES ingredients(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT uq_di_dish_ingredient UNIQUE (dish_id, ingredient_id)
);

CREATE OR REPLACE FUNCTION set_employee_code_prefix()
RETURNS TRIGGER AS $$
DECLARE
  prefix_val TEXT; -- Guardará el prefijo del restaurante
BEGIN

	-- Obtener el prefijo del restaurante asociado al nuevo empleado
	SELECT prefix INTO prefix_val
	FROM restaurants
	WHERE id = NEW.restaurant_id; 

	-- Si no se encuentra el restaurante o su prefijo, lanzar un error
	IF prefix_val IS NULL THEN
		RAISE EXCEPTION 'Restaurant prefix not found for id %', NEW.restaurant_id;
	END IF;

	-- Ejemplo: prefix + id con ceros (00001)

  	-- Evita duplicar prefijo si ya viene puesto
	-- Si el codigo no es igual al prefijo seguido de cualquier cosa, entonces lo modifica
	IF NEW.code NOT LIKE prefix_val || '%' THEN
		-- Modifica el valor de code antes de guardarlo en la base de datos
		-- := es asignación en PL/pgSQL (no es comparación)
		NEW.code := prefix_val || NEW.code;
	END IF;

	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_employee_code_prefix
BEFORE INSERT ON employee
FOR EACH ROW
EXECUTE FUNCTION set_employee_code_prefix();

CREATE OR REPLACE FUNCTION delete_created_orders_when_table_deleted()
RETURNS TRIGGER AS $$
BEGIN

    DELETE FROM orders o
    USING order_table ot
    WHERE ot.order_id = o.id
      AND ot.table_id = OLD.id
      AND o.status = 'CREATED';

    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_delete_created_orders_when_table_deleted
BEFORE DELETE ON tables_restaurant
FOR EACH ROW
EXECUTE FUNCTION delete_created_orders_when_table_deleted();

-- =========================================
-- PRIVILEGIOS: conceder al rol `admin`
-- Se ejecutan al final para aplicar sobre la base creada por Docker (POSTGRES_DB).
-- =========================================
GRANT USAGE ON SCHEMA public TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO admin;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO admin;