-- =========================================
-- USUARIO BACKEND (PostgreSQL)
-- =========================================

DROP ROLE IF EXISTS admin;
CREATE ROLE admin WITH LOGIN PASSWORD 'admin';

 
-- =========================================
-- BASE DE DATOS (PostgreSQL)
-- =========================================
-- NOTE:
-- When running inside Docker init (docker-entrypoint-initdb.d), psql is
-- already connected to the database specified by POSTGRES_DB (mi_db).
-- Do NOT DROP/CREATE databases here or run `\c` — instead create objects
-- in the database provided by the environment and apply grants at the end
-- of this script. This prevents errors like "cannot drop the currently open database".

-- The database itself is created by the container using POSTGRES_DB.


-- =========================================
-- TABLA: restaurants (PostgreSQL)
-- =========================================
CREATE TABLE restaurants (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(150) NOT NULL,
	description TEXT,
	email VARCHAR(150) NOT NULL,
	phone VARCHAR(25) NOT NULL,
	address VARCHAR(255) NOT NULL,
	logo_url VARCHAR(255),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_restaurants PRIMARY KEY (id)
);

-- =========================================
-- ROLES (PostgreSQL)
-- =========================================
CREATE TABLE roles (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(50) NOT NULL,
	CONSTRAINT pk_roles PRIMARY KEY (id)
);

INSERT INTO roles (name) VALUES
('MANAGER'),
('WAITER'),
('COOKER'),
('ADMIN');

-- =========================================
-- EMPLOYEES (PostgreSQL)
-- =========================================
CREATE TABLE employees (
	id INTEGER NOT NULL,
	name VARCHAR(150) NOT NULL,
	password_hash VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_employees PRIMARY KEY (id)
);

	-- =========================================
	-- CLIENTS (PostgreSQL)
	-- =========================================
	CREATE TABLE clients (
		id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
		restaurant_id INTEGER NOT NULL,
		name VARCHAR(150) NOT NULL,
		email VARCHAR(150) NOT NULL,
		password_hash VARCHAR(255) NOT NULL,
		created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		CONSTRAINT pk_clients PRIMARY KEY (id),
		CONSTRAINT uq_clients_restaurant_email UNIQUE (restaurant_id, email),
		CONSTRAINT fk_clients_restaurant FOREIGN KEY (restaurant_id)
			REFERENCES restaurants(id) ON DELETE RESTRICT ON UPDATE CASCADE
	);

	-- =========================================
	-- SECTIONS (PostgreSQL)
	-- =========================================
	CREATE TABLE table_sections (
		id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
		restaurant_id INTEGER NOT NULL,
		title VARCHAR(100) NOT NULL,
		CONSTRAINT pk_table_sections PRIMARY KEY (id),
		CONSTRAINT fk_table_sections_restaurant FOREIGN KEY (restaurant_id)
			REFERENCES restaurants(id) ON DELETE RESTRICT ON UPDATE CASCADE
	);

	-- =========================================
	-- TABLES (PostgreSQL)
	-- =========================================
	CREATE TABLE tables_restaurant (
		id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
		restaurant_id INTEGER NOT NULL,
		section_id INTEGER,
		name VARCHAR(50) NOT NULL,
		capacity INTEGER NOT NULL DEFAULT 2,
		pos_x INTEGER NOT NULL DEFAULT 0,
		pos_y INTEGER NOT NULL DEFAULT 0,
		active BOOLEAN NOT NULL DEFAULT TRUE,
		CONSTRAINT pk_tables_restaurant PRIMARY KEY (id),
		CONSTRAINT fk_tables_restaurant_restaurant FOREIGN KEY (restaurant_id)
			REFERENCES restaurants(id) ON DELETE RESTRICT ON UPDATE CASCADE,
		CONSTRAINT fk_tables_restaurant_section FOREIGN KEY (section_id)
			REFERENCES table_sections(id) ON DELETE SET NULL ON UPDATE CASCADE
	);

	-- =========================================
	-- CATEGORIES (PostgreSQL)
	-- =========================================
	CREATE TABLE categories (
		id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
		restaurant_id INTEGER NOT NULL,
		name VARCHAR(100) NOT NULL,
		CONSTRAINT pk_categories PRIMARY KEY (id),
		CONSTRAINT fk_categories_restaurant FOREIGN KEY (restaurant_id)
			REFERENCES restaurants(id) ON DELETE RESTRICT ON UPDATE CASCADE
	);

	-- =========================================
	-- DISHES (PostgreSQL)
	-- =========================================
	CREATE TABLE dishes (
		id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
		restaurant_id INTEGER NOT NULL,
		category_id INTEGER,
		name VARCHAR(150) NOT NULL,
		description TEXT,
		price NUMERIC(10,2) NOT NULL,
		available BOOLEAN NOT NULL DEFAULT TRUE,
		CONSTRAINT pk_dishes PRIMARY KEY (id),
		CONSTRAINT fk_dishes_restaurant FOREIGN KEY (restaurant_id)
			REFERENCES restaurants(id) ON DELETE RESTRICT ON UPDATE CASCADE,
		CONSTRAINT fk_dishes_category FOREIGN KEY (category_id)
			REFERENCES categories(id) ON DELETE SET NULL ON UPDATE CASCADE,
		CONSTRAINT uq_dishes_restaurant_name UNIQUE (restaurant_id, name)
	);

		-- =========================================
		-- ORDER STATUS (PostgreSQL)
		-- =========================================
		CREATE TABLE order_status (
			id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
			name VARCHAR(50) NOT NULL,
			CONSTRAINT pk_order_status PRIMARY KEY (id),
			CONSTRAINT uq_order_status_name UNIQUE (name)
		);

		INSERT INTO order_status (name) VALUES
		('CREATED'),
		('COOKED'),
		('DELIVERED'),
		('PAID');

		-- =========================================
		-- ORDER TYPE (PostgreSQL)
		-- =========================================
		CREATE TABLE order_type (
			id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
			name VARCHAR(50) NOT NULL,
			CONSTRAINT pk_order_type PRIMARY KEY (id),
			CONSTRAINT uq_order_type_name UNIQUE (name)
		);

		INSERT INTO order_type (name) VALUES
		('WEB'),
		('TABLE');

		-- =========================================
		-- ORDERS (PostgreSQL)
		-- =========================================
		CREATE TABLE orders (
			id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
			restaurant_id INTEGER NOT NULL,
			table_id INTEGER,
			order_type_id INTEGER NOT NULL,
			delivery_address VARCHAR(255),
			delivery_notes TEXT,
			client_id INTEGER,
			status_id INTEGER NOT NULL,
			total NUMERIC(10,2) NOT NULL DEFAULT 0.00,
			notes TEXT,
			created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
			CONSTRAINT pk_orders PRIMARY KEY (id),
			CONSTRAINT fk_orders_restaurant FOREIGN KEY (restaurant_id)
				REFERENCES restaurants(id) ON DELETE RESTRICT ON UPDATE CASCADE,
			CONSTRAINT fk_orders_table FOREIGN KEY (table_id)
				REFERENCES tables_restaurant(id) ON DELETE SET NULL ON UPDATE CASCADE,
			CONSTRAINT fk_orders_client FOREIGN KEY (client_id)
				REFERENCES clients(id) ON DELETE SET NULL ON UPDATE CASCADE,
			CONSTRAINT fk_orders_status FOREIGN KEY (status_id)
				REFERENCES order_status(id) ON DELETE RESTRICT ON UPDATE CASCADE,
			CONSTRAINT fk_orders_type FOREIGN KEY (order_type_id)
				REFERENCES order_type(id) ON DELETE RESTRICT ON UPDATE CASCADE
		);

		-- =========================================
		-- ORDER ITEMS (PostgreSQL)
		-- =========================================
		CREATE TABLE order_items (
			id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
			order_id INTEGER NOT NULL,
			dish_id INTEGER NOT NULL,
			notes TEXT,
			unit_price NUMERIC(10,2) NOT NULL,
			CONSTRAINT pk_order_items PRIMARY KEY (id),
			CONSTRAINT fk_order_items_order FOREIGN KEY (order_id)
				REFERENCES orders(id) ON DELETE CASCADE ON UPDATE CASCADE,
			CONSTRAINT fk_order_items_dish FOREIGN KEY (dish_id)
				REFERENCES dishes(id) ON DELETE RESTRICT ON UPDATE CASCADE
		);

			-- =========================================
			-- PAYMENTS (PostgreSQL)
			-- =========================================
			CREATE TABLE payments (
				id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
				order_id INTEGER NOT NULL,
				method VARCHAR(50) NOT NULL,
				amount NUMERIC(10,2) NOT NULL,
				paid_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
				CONSTRAINT pk_payments PRIMARY KEY (id),
				CONSTRAINT fk_payments_order FOREIGN KEY (order_id)
					REFERENCES orders(id) ON DELETE CASCADE ON UPDATE CASCADE
			);

			-- =========================================
			-- WEB PAGES (PostgreSQL)
			-- =========================================
			CREATE TABLE web_pages (
				id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
				restaurant_id INTEGER NOT NULL,
				page_type VARCHAR(50) NOT NULL,
				content JSONB,
				updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
				CONSTRAINT pk_web_pages PRIMARY KEY (id),
				CONSTRAINT fk_web_pages_restaurant FOREIGN KEY (restaurant_id)
					REFERENCES restaurants(id) ON DELETE CASCADE ON UPDATE CASCADE
			);

			-- =========================================
			-- EMPLOYEE RESTAURANTS (PostgreSQL)
			-- =========================================
			CREATE TABLE employee_restaurants (
				id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
				employee_dni INTEGER NOT NULL,
				restaurant_id INTEGER NOT NULL,
				role_id INTEGER NOT NULL,
				active BOOLEAN NOT NULL DEFAULT TRUE,
				email VARCHAR(150) NOT NULL,
				phone VARCHAR(25),
				start_date DATE NOT NULL,
				end_date DATE,
				position_notes TEXT,
				CONSTRAINT pk_employee_restaurants PRIMARY KEY (id),
				CONSTRAINT fk_er_employee FOREIGN KEY (employee_dni)
					REFERENCES employees(id) ON DELETE CASCADE ON UPDATE CASCADE,
				CONSTRAINT fk_er_restaurant FOREIGN KEY (restaurant_id)
					REFERENCES restaurants(id) ON DELETE CASCADE ON UPDATE CASCADE,
				CONSTRAINT uq_er_employee_restaurant UNIQUE (employee_dni, restaurant_id),
				CONSTRAINT fk_employees_role FOREIGN KEY (role_id)
					REFERENCES roles(id) ON DELETE RESTRICT ON UPDATE CASCADE,
				CONSTRAINT uq_employees_email UNIQUE (email)
			);

			-- =========================================
			-- INGREDIENTS (PostgreSQL)
			-- =========================================
			CREATE TABLE ingredients (
				id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
				restaurant_id INTEGER NOT NULL,
				name VARCHAR(150) NOT NULL,
				unit VARCHAR(50) NOT NULL,
				stock_quantity NUMERIC(12,3) NOT NULL DEFAULT 0,
				cost_unit NUMERIC(10,2),
				CONSTRAINT pk_ingredients PRIMARY KEY (id),
				CONSTRAINT fk_ingredients_restaurant FOREIGN KEY (restaurant_id)
					REFERENCES restaurants(id) ON DELETE RESTRICT ON UPDATE CASCADE,
				CONSTRAINT uq_ingredients_restaurant_name UNIQUE (restaurant_id, name)
			);

			-- =========================================
			-- DISH INGREDIENTS (PostgreSQL)
			-- =========================================
			CREATE TABLE dish_ingredients (
				id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
				dish_id INTEGER NOT NULL,
				ingredient_id INTEGER NOT NULL,
				quantity NUMERIC(12,3) NOT NULL,
				CONSTRAINT pk_dish_ingredients PRIMARY KEY (id),
				CONSTRAINT fk_di_dish FOREIGN KEY (dish_id)
					REFERENCES dishes(id) ON DELETE CASCADE ON UPDATE CASCADE,
				CONSTRAINT fk_di_ingredient FOREIGN KEY (ingredient_id)
					REFERENCES ingredients(id) ON DELETE RESTRICT ON UPDATE CASCADE,
				CONSTRAINT uq_di_dish_ingredient UNIQUE (dish_id, ingredient_id)
			);

				-- =========================================
				-- SCHEDULES (PostgreSQL)
				-- =========================================
				CREATE TABLE work_schedules (
					id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
					employee_restaurant_dni INTEGER NOT NULL,
					start_datetime TIMESTAMP NOT NULL,
					end_datetime TIMESTAMP NOT NULL,
					CONSTRAINT pk_work_schedules PRIMARY KEY (id),
					CONSTRAINT fk_ws_employee FOREIGN KEY (employee_restaurant_dni)
						REFERENCES employee_restaurants(id) ON DELETE CASCADE ON UPDATE CASCADE,
					CONSTRAINT chk_ws_dates CHECK (end_datetime > start_datetime)
				);

			-- =========================================
			-- PRIVILEGIOS: conceder al rol `admin`
			-- Se ejecutan al final para aplicar sobre la base creada por Docker (POSTGRES_DB).
			-- =========================================
			GRANT USAGE ON SCHEMA public TO admin;
			ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO admin;
			GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO admin;
			GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO admin;
			ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO admin;

