-- =========================================
-- USUARIO BACKEND (PostgreSQL)
-- =========================================

DROP ROLE IF EXISTS admin;
CREATE ROLE admin WITH LOGIN PASSWORD 'admin';

-- =========================================
-- TABLA: restaurants (PostgreSQL)
-- =========================================
CREATE TABLE restaurants (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	prefix VARCHAR(5) NOT NULL,
	name VARCHAR(150) NOT NULL,
	description TEXT,
	email VARCHAR(150) NOT NULL,
	phone VARCHAR(25) NOT NULL,
	address VARCHAR(255) NOT NULL,
	logo_url VARCHAR(255),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_restaurants PRIMARY KEY (id),
	CONSTRAINT uq_restaurants_prefix UNIQUE (prefix),
	CONSTRAINT uq_restaurants_email UNIQUE (email)
);

-- =========================================
-- EMPLOYEES (PostgreSQL)
-- =========================================
CREATE TYPE roles AS ENUM ('MANAGER', 'WAITER', 'COOKER', 'ADMIN');


CREATE TABLE employee (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	restaurant_id INTEGER NOT NULL,
	name VARCHAR(150) NOT NULL,
	role_name roles NOT NULL,
	active BOOLEAN NOT NULL DEFAULT TRUE,
	email VARCHAR(150) NOT NULL,
	phone VARCHAR(25),
	start_date DATE NOT NULL,
	end_date DATE,
	position_notes TEXT,
	code VARCHAR(255),
	password_hash VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_employee PRIMARY KEY (id),
	CONSTRAINT uq_employee_code_per_restaurant
		UNIQUE (restaurant_id, code),
	CONSTRAINT fk_employee_restaurant FOREIGN KEY (restaurant_id)
		REFERENCES restaurants(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- =========================================
-- SCHEDULES (PostgreSQL)
-- =========================================
CREATE TABLE work_schedules (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	employee_id INTEGER NOT NULL,
	start_datetime TIMESTAMP NOT NULL,
	end_datetime TIMESTAMP NOT NULL,
	CONSTRAINT pk_work_schedules PRIMARY KEY (id),
	CONSTRAINT fk_ws_employee FOREIGN KEY (employee_id)
		REFERENCES employee(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT chk_ws_dates CHECK (end_datetime > start_datetime)
);

-- =========================================
-- CLIENTS (PostgreSQL)
-- =========================================
CREATE TABLE clients (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	restaurant_id INTEGER NOT NULL,
	name VARCHAR(150) NOT NULL,
	email VARCHAR(150) NOT NULL,
	password_hash VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_clients PRIMARY KEY (id),
	CONSTRAINT uq_clients_restaurant_email UNIQUE (restaurant_id, email),
	CONSTRAINT fk_clients_restaurant FOREIGN KEY (restaurant_id)
		REFERENCES restaurants(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- =========================================
-- SECTIONS (PostgreSQL)
-- =========================================
CREATE TABLE table_sections (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	restaurant_id INTEGER NOT NULL,
	title VARCHAR(100) NOT NULL,
	CONSTRAINT pk_table_sections PRIMARY KEY (id),
	CONSTRAINT fk_table_sections_restaurant FOREIGN KEY (restaurant_id)
		REFERENCES restaurants(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TYPE table_status AS ENUM ('AVAILABLE', 'UNAVAILABLE', 'OCCUPIED', 'RESERVED');

-- =========================================
-- TABLES (PostgreSQL)
-- =========================================
CREATE TABLE tables_restaurant (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	restaurant_id INTEGER NOT NULL,
	section_id INTEGER NOT NULL,
	name VARCHAR(50) NOT NULL,
	capacity INTEGER NOT NULL DEFAULT 2,
	pos_x INTEGER NOT NULL DEFAULT 0,
	pos_y INTEGER NOT NULL DEFAULT 0,
	status table_status NOT NULL DEFAULT 'AVAILABLE',
	CONSTRAINT pk_tables_restaurant PRIMARY KEY (id),
	CONSTRAINT fk_tables_restaurant_restaurant FOREIGN KEY (restaurant_id)
		REFERENCES restaurants(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT fk_tables_restaurant_section FOREIGN KEY (section_id)
		REFERENCES table_sections(id) ON DELETE SET NULL ON UPDATE CASCADE
);

-- =========================================
-- CATEGORIES (PostgreSQL)
-- =========================================
CREATE TABLE categories (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	restaurant_id INTEGER NOT NULL,
	name VARCHAR(100) NOT NULL,
	CONSTRAINT pk_categories PRIMARY KEY (id),
	CONSTRAINT fk_categories_restaurant FOREIGN KEY (restaurant_id)
		REFERENCES restaurants(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- =========================================
-- DISHES (PostgreSQL)
-- =========================================
CREATE TABLE dishes (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	restaurant_id INTEGER NOT NULL,
	category_id INTEGER,
	name VARCHAR(150) NOT NULL,
	description TEXT,
	price NUMERIC(10,2) NOT NULL,
	available BOOLEAN NOT NULL DEFAULT TRUE,
	CONSTRAINT pk_dishes PRIMARY KEY (id),
	CONSTRAINT fk_dishes_restaurant FOREIGN KEY (restaurant_id)
		REFERENCES restaurants(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT fk_dishes_category FOREIGN KEY (category_id)
		REFERENCES categories(id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT uq_dishes_restaurant_name UNIQUE (restaurant_id, name)
);

-- =========================================
-- ORDER STATUS (PostgreSQL)
-- =========================================
CREATE TABLE order_status (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(50) NOT NULL,
	CONSTRAINT pk_order_status PRIMARY KEY (id),
	CONSTRAINT uq_order_status_name UNIQUE (name)
);

INSERT INTO order_status (name) VALUES
('CREATED'),
('COOKED'),
('DELIVERED'),
('PAID');

-- =========================================
-- ORDER TYPE (PostgreSQL)
-- =========================================
CREATE TABLE order_type (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(50) NOT NULL,
	CONSTRAINT pk_order_type PRIMARY KEY (id),
	CONSTRAINT uq_order_type_name UNIQUE (name)
);

INSERT INTO order_type (name) VALUES
('WEB'),
('TABLE');

-- =========================================
-- ORDERS (PostgreSQL)
-- =========================================
CREATE TABLE orders (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	restaurant_id INTEGER NOT NULL,
	table_id INTEGER,
	order_type_id INTEGER NOT NULL,
	delivery_address VARCHAR(255),
	delivery_notes TEXT,
	client_id INTEGER,
	status_id INTEGER NOT NULL,
	total NUMERIC(10,2) NOT NULL DEFAULT 0.00,
	notes TEXT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_orders PRIMARY KEY (id),
	CONSTRAINT fk_orders_restaurant FOREIGN KEY (restaurant_id)
		REFERENCES restaurants(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT fk_orders_table FOREIGN KEY (table_id)
		REFERENCES tables_restaurant(id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT fk_orders_client FOREIGN KEY (client_id)
		REFERENCES clients(id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT fk_orders_status FOREIGN KEY (status_id)
		REFERENCES order_status(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT fk_orders_type FOREIGN KEY (order_type_id)
		REFERENCES order_type(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- =========================================
-- ORDER ITEMS (PostgreSQL)
-- =========================================
CREATE TABLE order_items (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	order_id INTEGER NOT NULL,
	dish_id INTEGER NOT NULL,
	notes TEXT,
	unit_price NUMERIC(10,2) NOT NULL,
	CONSTRAINT pk_order_items PRIMARY KEY (id),
	CONSTRAINT fk_order_items_order FOREIGN KEY (order_id)
		REFERENCES orders(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_order_items_dish FOREIGN KEY (dish_id)
		REFERENCES dishes(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- =========================================
-- PAYMENTS (PostgreSQL)
-- =========================================
CREATE TABLE payments (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	order_id INTEGER NOT NULL,
	method VARCHAR(50) NOT NULL,
	amount NUMERIC(10,2) NOT NULL,
	paid_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_payments PRIMARY KEY (id),
	CONSTRAINT fk_payments_order FOREIGN KEY (order_id)
		REFERENCES orders(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- =========================================
-- WEB PAGES (PostgreSQL)
-- =========================================
CREATE TABLE web_pages (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	restaurant_id INTEGER NOT NULL,
	page_type VARCHAR(50) NOT NULL,
	content JSONB,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_web_pages PRIMARY KEY (id),
	CONSTRAINT fk_web_pages_restaurant FOREIGN KEY (restaurant_id)
		REFERENCES restaurants(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- =========================================
-- INGREDIENTS (PostgreSQL)
-- =========================================
CREATE TABLE ingredients (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	restaurant_id INTEGER NOT NULL,
	name VARCHAR(150) NOT NULL,
	unit VARCHAR(50) NOT NULL,
	stock_quantity NUMERIC(12,3) NOT NULL DEFAULT 0,
	cost_unit NUMERIC(10,2),
	CONSTRAINT pk_ingredients PRIMARY KEY (id),
	CONSTRAINT fk_ingredients_restaurant FOREIGN KEY (restaurant_id)
		REFERENCES restaurants(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT uq_ingredients_restaurant_name UNIQUE (restaurant_id, name)
);

-- =========================================
-- DISH INGREDIENTS (PostgreSQL)
-- =========================================
CREATE TABLE dish_ingredients (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	dish_id INTEGER NOT NULL,
	ingredient_id INTEGER NOT NULL,
	quantity NUMERIC(12,3) NOT NULL,
	CONSTRAINT pk_dish_ingredients PRIMARY KEY (id),
	CONSTRAINT fk_di_dish FOREIGN KEY (dish_id)
		REFERENCES dishes(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_di_ingredient FOREIGN KEY (ingredient_id)
		REFERENCES ingredients(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT uq_di_dish_ingredient UNIQUE (dish_id, ingredient_id)
);

CREATE OR REPLACE FUNCTION set_employee_code_prefix()
RETURNS TRIGGER AS $$
DECLARE
  prefix_val TEXT; -- Guardará el prefijo del restaurante
BEGIN

	-- Obtener el prefijo del restaurante asociado al nuevo empleado
	SELECT prefix INTO prefix_val
	FROM restaurants
	WHERE id = NEW.restaurant_id; 

	-- Si no se encuentra el restaurante o su prefijo, lanzar un error
	IF prefix_val IS NULL THEN
		RAISE EXCEPTION 'Restaurant prefix not found for id %', NEW.restaurant_id;
	END IF;

	-- Ejemplo: prefix + id con ceros (00001)

  	-- Evita duplicar prefijo si ya viene puesto
	-- Si el codigo no es igual al prefijo seguido de cualquier cosa, entonces lo modifica
	IF NEW.code NOT LIKE prefix_val || '%' THEN
		-- Modifica el valor de code antes de guardarlo en la base de datos
		-- := es asignación en PL/pgSQL (no es comparación)
		NEW.code := prefix_val || NEW.code;
	END IF;

	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_employee_code_prefix
BEFORE INSERT ON employee
FOR EACH ROW
EXECUTE FUNCTION set_employee_code_prefix();

-- =========================================
-- Vista para movil
-- Para recoger los datos necesarios de la app de movil mas rapido
-- =========================================
-- Ejemplo de llamada a dishes_restaurant: SELECT * FROM dishes_restaurant WHERE restaurant_id = 'id del restaurante buscado'
CREATE VIEW data_restaurant_dishes AS
SELECT 
	d.id,
	d.name,
	c.name as category_name,
	d.description,
	d.price,
	d.available,
	d.restaurant_id
FROM dishes d
JOIN categories c on d.category_id = c.id;

CREATE VIEW restaurant_web_orders AS
SELECT 
	o.id AS order_id,
	o.restaurant_id,
	o.table_id,
	os.name AS status_name,
	o.total,
	o.notes,
	o.created_at,
	oi.dish_id
FROM orders o
JOIN order_status os ON o.status_id = os.id
JOIN order_items oi ON o.id = oi.order_id
WHERE o.order_type_id = 1;-- Pedidos web 'WEB'

CREATE VIEW restaurant_table_orders AS
SELECT 
	o.id AS order_id,
	o.restaurant_id,
	o.table_id,
	os.name AS status_name,
	o.total,
	o.notes,
	o.created_at,
	oi.dish_id
FROM orders o
JOIN order_status os ON o.status_id = os.id
JOIN order_items oi ON o.id = oi.order_id
WHERE o.order_type_id = 2;-- Pedidos en mesa 'TABLE'

INSERT INTO restaurants (prefix, name, description, email, phone, address, logo_url)
VALUES
('MAD', 'Restaurante Madrid', 'Restaurante de cocina española', 'madrid@rest.com', '912345678', 'Calle Mayor 1, Madrid', 'https://example.com/logo_mad.png'),
('BCN', 'Restaurante Barcelona', 'Restaurante de tapas y paellas', 'barcelona@rest.com', '934567890', 'Rambla 10, Barcelona', 'https://example.com/logo_bcn.png');

-- =========================================
-- INSERTAR EMPLEADOS
-- =========================================
-- Empleados del restaurante Madrid
INSERT INTO employee (restaurant_id, name, role_name, email, phone, start_date, code, password_hash)
VALUES
(1, 'Juan Perez', 'MANAGER', 'juan.mad@rest.com', '600111222', '2023-01-01', '00001', 'hash1'),
(1, 'Maria Lopez', 'WAITER', 'maria.mad@rest.com', '600333444', '2023-02-01', '00002', 'hash2');

-- Empleados del restaurante Barcelona
INSERT INTO employee (restaurant_id, name, role_name, email, phone, start_date, code, password_hash)
VALUES
(2, 'Carlos Gomez', 'COOKER', 'carlos.bcn@rest.com', '611111222', '2023-03-01', '00001', 'hash3'),
(2, 'Ana Torres', 'WAITER', 'ana.bcn@rest.com', '611333444', '2023-04-01', '00002', 'hash4');

-- =========================================
-- INSERTAR HORARIOS DE TRABAJO
-- =========================================
-- Horarios para empleados del restaurante Madrid
INSERT INTO work_schedules (employee_id, start_datetime, end_datetime)
VALUES
(1, '2026-03-20 09:00:00', '2026-03-20 17:00:00'),
(1, '2026-03-21 10:00:00', '2026-03-21 18:00:00'),
(2, '2026-03-20 12:00:00', '2026-03-20 20:00:00'),
(2, '2026-03-21 14:00:00', '2026-03-21 22:00:00');

-- Horarios para empleados del restaurante Barcelona
INSERT INTO work_schedules (employee_id, start_datetime, end_datetime)
VALUES
(3, '2026-03-20 08:00:00', '2026-03-20 16:00:00'),
(3, '2026-03-21 09:00:00', '2026-03-21 17:00:00'),
(4, '2026-03-20 13:00:00', '2026-03-20 21:00:00'),
(4, '2026-03-21 15:00:00', '2026-03-21 23:00:00');

-- =========================================
-- PRIVILEGIOS: conceder al rol `admin`
-- Se ejecutan al final para aplicar sobre la base creada por Docker (POSTGRES_DB).
-- =========================================
GRANT USAGE ON SCHEMA public TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO admin;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO admin;

